name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code du repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Activer la clé SSH pour le serveur
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3️⃣ Déployer le code sur le serveur
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no raoul@lesacteursduweb.fr "
            cd ~/www_github || exit
            git pull origin main
          "
