name: "PHPUnit Tests" # nom du workflow

on:
  push: {}            # déclenche sur push (tu peux restreindre sur branches: [main])
  pull_request: {}    # déclenche sur PR

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4   # récupère le code du repo

      - name: Set up PHP
        uses: shivammathur/setup-php@v2  # action qui installe PHP versions et extensions
        with:
          php-version: '8.2'            # version PHP à adapter

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist
        # installe les dépendances via composer

      - name: Run PHPUnit
        run: vendor/bin/phpunit --testsuite default --colors=always
        # exécute les tests unitaires; échec -> job rouge
